services:
  umkm-pos-db:
    image: mysql:8.0
    container_name: umkm-pos-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_umkm_pos
    networks:
      - devbox_devnet
    restart: always

  umkm-pos-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: umkm-pos-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:***@umkm-pos-db:3306/db_umkm_pos
      - JWT_SECRET=supersecret2026
      - JWT_EXPIRES_IN=7d
      - API_PREFIX=api
      - API_VERSION=v1
      - CORS_ORIGIN=https://app.insell.id,https://www.app.insell.id,https://www.insell.id,https://insell.id,http://localhost:3000
    depends_on:
      - umkm-pos-db
    networks:
      - devbox_devnet
    restart: always

  umkm-pos-landing:
    build:
      context: .
      dockerfile: apps/landing/Dockerfile
    container_name: umkm-pos-landing
    expose:
      - "80"
    networks:
      - devbox_devnet
    restart: always

  umkm-pos-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: https://api.insell.id
    container_name: umkm-pos-web
    expose:
      - "80"
    networks:
      - devbox_devnet
    restart: always

networks:
  devbox_devnet:
    external: true
