services:
  umkm-pos-db:
    image: mysql:8.0
    container_name: umkm-pos-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_umkm_pos
    networks:
      - devbox_devnet
    restart: always

  umkm-pos-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: umkm-pos-api
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:rootpassword@umkm-pos-db:3306/db_umkm_pos
      - JWT_SECRET=supersecret2026
      - JWT_EXPIRES_IN=7d
      - API_PREFIX=api
      - API_VERSION=v1
      - CORS_ORIGIN=https://app.insell.web.id,https://www.insell.web.id,https://insell.web.id,http://localhost:3000
    depends_on:
      - umkm-pos-db
    networks:
      - devbox_devnet
    restart: always

networks:
  devbox_devnet:
    external: true
