CREATE TABLE `outlet_product_inventory` (
  `id` char(36) NOT NULL DEFAULT (uuid()),
  `merchant_id` char(36) NOT NULL,
  `outlet_id` char(36) NOT NULL,
  `product_id` char(36) NOT NULL,
  `stock_qty` int NOT NULL DEFAULT 0,
  `min_stock` int NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` char(36) DEFAULT NULL,
  `updated_by` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_outlet_product_inventory` (`outlet_id`,`product_id`),
  KEY `idx_outlet_product_inventory_merchant` (`merchant_id`),
  KEY `idx_outlet_product_inventory_outlet` (`outlet_id`),
  KEY `idx_outlet_product_inventory_product` (`product_id`),
  CONSTRAINT `outlet_product_inventory_ibfk_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `outlet_product_inventory_ibfk_outlet` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `outlet_product_inventory_ibfk_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
);

CREATE TABLE `inventory_movements` (
  `id` char(36) NOT NULL DEFAULT (uuid()),
  `merchant_id` char(36) NOT NULL,
  `outlet_id` char(36) NOT NULL,
  `product_id` char(36) NOT NULL,
  `change_qty` int NOT NULL,
  `stock_after` int NULL,
  `reason` varchar(50) NOT NULL,
  `ref_type` varchar(50) DEFAULT NULL,
  `ref_id` char(36) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` char(36) DEFAULT NULL,
  `updated_by` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_movements_merchant` (`merchant_id`),
  KEY `idx_inventory_movements_outlet` (`outlet_id`),
  KEY `idx_inventory_movements_product` (`product_id`),
  KEY `idx_inventory_movements_ref` (`ref_id`),
  CONSTRAINT `inventory_movements_ibfk_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `inventory_movements_ibfk_outlet` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `inventory_movements_ibfk_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
);
